controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true
    
    # Declare controllers
    joint1_controller:
      type: robot_joint_controller/RobotJointController
    
    joint2_controller:
      type: robot_joint_controller/RobotJointController
    
    joint3_controller:
      type: robot_joint_controller/RobotJointController
    
    joint4_controller:
      type: robot_joint_controller/RobotJointController
    
    joint5_controller:
      type: robot_joint_controller/RobotJointController
    
    joint6_controller:
      type: robot_joint_controller/RobotJointController
    
    gripper_controller:
      type: robot_joint_controller/RobotJointController
    
    robot_joint_controller_group:
      type: robot_joint_controller/RobotJointControllerGroup
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# Individual joint controller parameters
joint1_controller:
  ros__parameters:
    joints: "joint1"

joint2_controller:
  ros__parameters:
    joints: "joint2"

joint3_controller:
  ros__parameters:
    joints: "joint3"

joint4_controller:
  ros__parameters:
    joints: "joint4"

joint5_controller:
  ros__parameters:
    joints: "joint5"

joint6_controller:
  ros__parameters:
    joints: "joint6"

gripper_controller:
  ros__parameters:
    joints: "gripper_1_joint"

# Group controller parameters
robot_joint_controller_group:
  ros__parameters:
    joints:
      - "joint1"
      - "joint2"
      - "joint3"
      - "joint4"
      - "joint5"
      - "joint6"

# Joint state broadcaster
joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true

